// Web Worker hosting the Trax wasm engine. The main thread stays responsive while
// the engine thinks (up to 120s); per-depth reports stream out live through the
// js_on_depth import. Protocol: postMessage({id, line}) in, {id, resp} out, plus
// unsolicited {depth: "..."} lines during ENGINE calls and one {ready} after init.

'use strict';

// The knowledge files served alongside the page (repo root). Directory listings
// don't exist on GitHub Pages, so the threat file names are configured here -
// keep in sync with the threat/ directory. Missing files degrade gracefully.
// Fallback list only: boot() first fetches threat/manifest.txt (one filename per
// line, generated by `make deploy` from the actual directory), so new threat
// files reach the site without touching this code. The native engine scans the
// directory; the manifest is how a browser, which cannot, keeps parity with it.
const THREAT_FILES = ['3stage.txt', 'L-threats.txt', 'all.txt', 'edge.txt', 'threats.txt'];

let ex = null;
let enc = new TextEncoder();
let dec = new TextDecoder();

function mem() { return new Uint8Array(ex.memory.buffer); }
function put(str) {
  const b = enc.encode(str);
  const p = ex.tx_alloc(b.length || 1);
  if (b.length) mem().set(b, p);
  return { p, len: b.length };
}
function resp(len) {
  const base = ex.tx_resp_ptr();
  return dec.decode(mem().slice(base, base + len));
}
function call(line) {
  const { p, len } = put(line);
  const rl = ex.tx_call(p, len);
  ex.tx_dealloc(p, len || 1);
  return resp(rl);
}

// The worker's own URL carries ?v=<build> (app.js appends it); stamping the
// same version onto every asset fetch makes each deploy a brand-new URL set,
// defeating both browser caches and the Pages CDN's max-age=600 edges -
// 'no-cache' alone only forces revalidation, which a CDN edge can still
// answer stale within its TTL.
const V = (typeof location === 'object' && location && location.search) ? location.search : '';
// Knowledge files (books, threats, replies) change BETWEEN builds - curation
// is their whole life - so the build-id ?v= alone cannot bust them: an
// edited neverplay.trx redeployed under the same build keeps a byte-identical
// URL and rides the CDN-edge lottery. Artifacts stay build-versioned (the
// wasm is large and build-tied); knowledge gets a per-session timestamp -
// small text files, always fetched fresh at worker boot.
const K = (V ? V + '&_=' : '?_=') + Date.now();

async function fetchText(url) {
  try {
    const r = await fetch(url + K, { cache: 'no-cache' });
    return r.ok ? await r.text() : '';
  } catch (e) { return ''; }
}

async function boot() {
  // The manifest lets the browser discover threat files it cannot glob; the
  // native engine scans the directory, so this keeps the two in parity.
  const manifest = (await fetchText('threat/manifest.txt')).split(/\r?\n/)
    .map((l) => l.trim()).filter((l) => l && !l.startsWith('#') && l !== 'manifest.txt');
  const threatFiles = manifest.length ? manifest : THREAT_FILES;
  const [wasmBytes, always, never, replies0, repliesDraw, replies12, replies12d, evalc, ...threatParts] = await Promise.all([
    fetch('trax.wasm' + V, { cache: 'no-cache' }).then((r) => {
      if (!r.ok) throw new Error('trax.wasm not found next to index.html');
      return r.arrayBuffer();
    }),
    fetchText('book/alwaysplay.trx'),
    fetchText('book/neverplay.trx'),
    // Uniform reply names since rust275; the bare replies.txt is the 8x8
    // legacy fossil, fetched only when the new name is absent (transition aid).
    fetchText('book/replies-8x8.txt').then((t) => t || fetchText('book/replies.txt')),
    fetchText('book/replies-8x8-draw.txt'),
    fetchText('book/replies-12x12.txt'),
    fetchText('book/replies-12x12-draw.txt'),
    fetchText('eval.conf'),
    ...threatFiles.map((f) => fetchText('threat/' + f)),
  ]);
  const threats = threatParts.join('\n');

  const { instance } = await WebAssembly.instantiate(wasmBytes, {
    env: {
      js_now_ms: () => performance.now(), // monotonic - immune to wall-clock jumps mid-think
      js_on_depth: (ptr, len) => {
        const line = dec.decode(new Uint8Array(instance.exports.memory.buffer).slice(ptr, ptr + len));
        postMessage({ depth: line });
      },
    },
  });
  ex = instance.exports;

  // The 12x12 family's replies ride in the main buffer under [variant]
  // sections - the six-buffer wasm ABI stays put.
  let replies = replies0;
  if (replies12.trim()) replies += `\n[12x12]\n${replies12}`;
  if (replies12d.trim()) replies += `\n[12x12-draw]\n${replies12d}`;
  const bufs = [threats, always, never, replies, repliesDraw, evalc].map(put);
  const il = ex.tx_init(bufs[0].p, bufs[0].len, bufs[1].p, bufs[1].len, bufs[2].p, bufs[2].len, bufs[3].p, bufs[3].len, bufs[4].p, bufs[4].len, bufs[5].p, bufs[5].len);
  const initR = JSON.parse(resp(il));
  bufs.forEach((b) => ex.tx_dealloc(b.p, b.len || 1));
  if (!initR.ok) throw new Error('engine init failed: ' + initR.error);
  let build = '';
  try { build = JSON.parse(call('VERSION')).build || ''; } catch (e) { /* older wasm */ }
  // Size the persistent TT to the device (rust331). No browser reports its
  // true eviction budget, so this is a tiered heuristic at ~98 MB per million
  // entries: navigator.deviceMemory when present (Chromium only, quantized
  // 0.25..8 GB, absent on Safari/Firefox), else phone-vs-desktop from the
  // user agent and touch signals. Phones evict a 1 GB tab; laptops shrug.
  const ttCap = chooseTtCap();
  try { call('TT_CAP ' + ttCap.entries); } catch (e) { /* older wasm: default stands */ }
  postMessage({ ready: true, threats: initR.threats, book: initR.book, replies: initR.replies || 0, build,
                ttCap: ttCap.entries, ttTier: ttCap.tier });
}

// Device -> TT entry cap. Exported shape for embedders: {entries, tier}.
function chooseTtCap() {
  const nav = (typeof navigator !== 'undefined') ? navigator : {};
  const ua = (nav.userAgent || '').toLowerCase();
  const phoneUa = /iphone|ipod|android.*mobile|windows phone|mobile safari/.test(ua);
  const tabletUa = /ipad|android(?!.*mobile)|tablet/.test(ua);
  const touchOnly = (nav.maxTouchPoints || 0) > 1 && !/windows nt/.test(ua) && !/macintosh/.test(ua);
  const dm = nav.deviceMemory; // GB, quantized; undefined on Safari/Firefox
  let tier, entries;
  const isPhone = phoneUa || (touchOnly && !tabletUa);
  if (typeof dm === 'number') {
    // Spend about a quarter of reported RAM, capped at the build default (1 GB).
    if (dm <= 1)      { tier = 'tiny (<=1 GB)';    entries = 1_000_000; }   // ~100 MB
    else if (dm <= 2) { tier = 'small (2 GB)';     entries = 2_000_000; }   // ~200 MB
    else if (dm <= 4) { tier = 'medium (4 GB)';    entries = 5_000_000; }   // ~500 MB
    else              { tier = 'large (>=8 GB)';   entries = 10_000_000; }  // ~1 GB, the default
    // Phones evict by TAB size, not RAM headroom: a 4 GB phone still loses a
    // 500 MB tab. Phone-ness caps the memory tier at the safe phone number.
    if (isPhone && entries > 2_000_000) { entries = 2_000_000; tier += ', phone-capped'; }
  } else if (isPhone) {
    tier = 'phone (UA)';   entries = 2_000_000;   // ~200 MB - the safe phone number
  } else if (tabletUa) {
    tier = 'tablet (UA)';  entries = 4_000_000;   // ~400 MB
  } else {
    tier = 'desktop (UA)'; entries = 10_000_000;  // ~1 GB
  }
  return { entries, tier };
}

const queue = [];
let booted = false;

onmessage = (e) => {
  if (!booted) { queue.push(e.data); return; }
  const { id, line } = e.data;
  const r = call(line);
  postMessage({ id, resp: r });
};

boot().then(() => {
  booted = true;
  for (const m of queue) {
    const r = call(m.line);
    postMessage({ id: m.id, resp: r });
  }
}).catch((err) => {
  postMessage({ fatal: String(err && err.message || err) });
});
